services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql-flask
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3311:3306"
    volumes:
      - "./data:/var/lib/mysql"
volumes:
  data: